#!/usr/bin/env php
<?php

// installed via composer?

if (file_exists($autoload = __DIR__.'/../../autoload.php')) {
    require_once $autoload;
} else {
    require_once __DIR__.'/vendor/autoload.php';
}

use AmaxLab\PhpSpeller\Console\Application;

$app = new Application();
$app->run();

//echo PHP_EOL;
